definitions:
  controller.CreateOrgResponse:
    properties:
      orgId:
        type: integer
    type: object
  controller.CreateProjectRequest:
    properties:
      name:
        type: string
    type: object
  controller.CreateProjectResponse:
    properties:
      projId:
        type: integer
    type: object
  controller.DeleteOrgResponse:
    properties:
      status:
        type: boolean
    type: object
  controller.DeleteProjectResponse:
    properties:
      status:
        type: boolean
    type: object
  controller.GetOrgResponse:
    properties:
      org:
        $ref: '#/definitions/datastore.Organization'
      projectIds:
        items:
          type: string
        type: array
    type: object
  controller.GetProjectResponse:
    properties:
      project:
        $ref: '#/definitions/datastore.Project'
    type: object
  controller.ListOrgResponse:
    properties:
      orgList:
        items:
          $ref: '#/definitions/datastore.Organization'
        type: array
    type: object
  controller.ListProjectResponse:
    properties:
      projectList:
        items:
          $ref: '#/definitions/datastore.Project'
        type: array
    type: object
  controller.UpdateOrgRequest:
    properties:
      name:
        type: string
    type: object
  controller.UpdateOrgResponse:
    properties:
      status:
        type: boolean
    type: object
  controller.UpdateProjectRequest:
    properties:
      name:
        type: string
    type: object
  controller.UpdateProjectResponse:
    properties:
      status:
        type: boolean
    type: object
  datastore.Organization:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  datastore.Project:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      orgId:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact:
    email: lark@pointgoal.io
    name: PointGoal team
    url: https://github.com/pointgoal/workstation
  description: This is workstation backend with rk-boot.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Workstation
  version: "1.0"
paths:
  /v1/org:
    get:
      operationId: "1"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ListOrgResponse'
      summary: List organizations
      tags:
      - organization
    put:
      operationId: "3"
      parameters:
      - description: Organization name
        in: query
        name: orgName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CreateOrgResponse'
      summary: Create organization
      tags:
      - organization
  /v1/org/{orgId}:
    delete:
      operationId: "4"
      parameters:
      - description: Organization Id
        in: query
        name: orgId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.DeleteOrgResponse'
      summary: Delete organization
      tags:
      - organization
    get:
      operationId: "2"
      parameters:
      - description: Organization Id
        in: path
        name: orgId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetOrgResponse'
      summary: Get organization
      tags:
      - organization
    post:
      operationId: "5"
      parameters:
      - description: Organization
        in: body
        name: org
        required: true
        schema:
          $ref: '#/definitions/controller.UpdateOrgRequest'
      - description: Organization Id
        in: query
        name: orgId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UpdateOrgResponse'
      summary: Update organization
      tags:
      - organization
  /v1/org/{orgId}/proj:
    get:
      operationId: "6"
      parameters:
      - description: Organization Id
        in: query
        name: orgId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ListProjectResponse'
      summary: List projects
      tags:
      - project
    put:
      operationId: "8"
      parameters:
      - description: Organization Id
        in: query
        name: orgId
        required: true
        type: integer
      - description: Project
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/controller.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CreateProjectResponse'
      summary: create project
      tags:
      - project
  /v1/org/{orgId}/proj/{projId}:
    delete:
      operationId: "9"
      parameters:
      - description: Organization Id
        in: query
        name: orgId
        required: true
        type: integer
      - description: Project Id
        in: query
        name: projId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.DeleteProjectResponse'
      summary: delete project
      tags:
      - project
    get:
      operationId: "7"
      parameters:
      - description: Organization Id
        in: query
        name: orgId
        required: true
        type: integer
      - description: Project Id
        in: query
        name: projId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetProjectResponse'
      summary: Get project
      tags:
      - project
    post:
      operationId: "10"
      parameters:
      - description: Organization Id
        in: query
        name: orgId
        required: true
        type: integer
      - description: Project Id
        in: query
        name: projId
        required: true
        type: integer
      - description: Project
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/controller.UpdateProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UpdateProjectResponse'
      summary: update project
      tags:
      - project
swagger: "2.0"
